image: gitlab-registry.cern.ch/ep-dt-di/daq/daqling:latest

stages:
    - compilation
    - testing

# Default compile jobs
.compile:
    stage: compilation
    script:
        - mkdir build
        - cd build
        - cmake3 -DENABLE_SANITIZE=OFF -DBUILD_Dummy=ON ..
        - make -j$(nproc)
    artifacts:
        paths:
            - build
        expire_in: 1 hours

cmp:cc7-gcc:
    extends: .compile
    before_script:
        - source cmake/setup.sh

# Default tests
.test:
    stage: testing
    script:
        - cd build/
        - ctest3 --output-on-failure -j4

tst:cc7-gcc:
    extends: .test
    dependencies:
        - cmp:cc7-gcc
    before_script:
        - source cmake/setup.sh

format:
    stage: formatting
    script:
        - source cmake/setup.sh
        - cd build
        - cmake3 ..
        - make check-format
