image: gitlab-registry.cern.ch/ep-dt-di/daq/daqling:develop

stages:
    - compilation
    - testing

# Default compile jobs
compile:
    stage: compilation
    script:
        - mkdir build
        - cd build
        - cmake -DENABLE_SANITIZE=OFF -DBUILD_Dummy=ON ..
        - make -j$(nproc)
    artifacts:
        paths:
            - build
        expire_in: 1 hours
    before_script:
        - source cmake/setup.sh /daqling-spack-repo

# Default tests
test:
    stage: testing
    script:
        - cd build/
        - ctest --output-on-failure -j4
    dependencies:
        - compile
    before_script:
        - source cmake/setup.sh /daqling-spack-repo

format:
    stage: testing
    script:
        - cd build
        - make check-format
    dependencies:
        - compile
    before_script:
        - source cmake/setup.sh /daqling-spack-repo
    allow_failure: true
tidy:
    stage: testing
    script:
        - cd build
        - make check-lint
    dependencies:
        - compile
    before_script:
        - source cmake/setup.sh /daqling-spack-repo
    allow_failure: true
