stages:
    - compilation
    - testing
    - formatting

# Default compile jobs
.compile:
    stage: compilation
    script:
        - mkdir build
        - cd build
        - cmake3 -DENABLE_SANITIZE=OFF -DBUILD_Dummy=ON ..
        - make -j$(nproc)
    artifacts:
        paths:
            - build
        expire_in: 1 hours

cmp:cc7-gcc:
    extends: .compile
    image: clicdp/cc7-base
    before_script:
        - yum install -y ansible
        - ansible-playbook ansible/set-up-host.yml -vvv --tags minimal
        - source cmake/setup.sh

# Default tests
.test:
    stage: testing
    script:
        - cd build/
        - ctest3 --output-on-failure -j4

tst:cc7-gcc:
    extends: .test
    dependencies:
        - cmp:cc7-gcc
    before_script:
        - yum install -y ansible
        - ansible-playbook ansible/set-up-host.yml -vvv --tags minimal
        - source cmake/setup.sh
    image: clicdp/cc7-base

format:
    stage: formatting
    image: clicdp/cc7-base
    script:
        - yum install -y ansible
        - ansible-playbook ansible/set-up-host.yml -vvv --tags minimal
        - source cmake/setup.sh
        - cd build
        - source /opt/rh/llvm-toolset-7/enable
        - cmake3 ..
        - make check-format
