image: gitlab-registry.cern.ch/ep-dt-di/daq/daqling:latest

stages:
    - compilation
    - testing

# Default compile jobs
compile:
    stage: compilation
    script:
        - mkdir build
        - cd build
        - cmake3 -DENABLE_SANITIZE=OFF -DBUILD_Dummy=ON ..
        - make -j$(nproc)
    artifacts:
        paths:
            - build
        expire_in: 1 hours
    before_script:
        - source cmake/setup.sh

# Default tests
test:
    stage: testing
    script:
        - cd build/
        - ctest3 --output-on-failure -j4
    dependencies:
        - compile
    before_script:
        - source cmake/setup.sh

format:
    stage: testing
    script:
        - cd build
        - make check-format
    dependencies:
        - compile
    before_script:
        - source cmake/setup.sh
