- name: Install pyzmq
  pip:
    name: pyzmq
    executable: pip3

- name: Install jsonschema
  pip: 
    name: jsonschema
    executable: pip3 

- name: Install jsonref
  pip: 
    name: jsonref
    executable: pip3 
