- name: Install python3-devel [RedHat]
  become: yes
  ignore_errors: yes
  package:
    name: python3-devel
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install python3-dev [Debian]
  become: yes
  ignore_errors: yes
  package:
    name: python3-dev
  when: ansible_facts['os_family'] == 'Debian'

- name: Install virtual-env
  pip:
    name: "{{packages}}"
    executable: pip3
  vars:
    packages:
    - virtualenv
    - importlib-metadata

- name: Manually create the initial virtualenv
  become: no
  command:
    cmd: python3 -m venv "{{base_dir}}/etc/daqling_venv" 
    creates: "{{base_dir}}/etc/daqling_venv"
  vars:
    base_dir: "{{ lookup('env','DAQLING_LOCATION') }}"

- name: Install control python deps
  pip:
    requirements: "{{base_dir}}/etc/control-requirements.txt"
    virtualenv: "{{base_dir}}/etc/daqling_venv"

  vars:
    base_dir: "{{ lookup('env','DAQLING_LOCATION') }}"
