#Marco Boretto <marco.boretto@cern.ch> 2019
---

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - vim
    - wget
    - cmake3
    - mlocate
    - graphviz

- name: Updatedb
  shell: updatedb
