- name: Install Grafana
  yum:
    name: https://dl.grafana.com/oss/release/grafana-6.2.4-1.x86_64.rpm

- name: Open port 3000 on firewalld for Grafana
  firewalld:
    zone: public
    port: 3000/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enabling Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    daemon_reload: yes
  notify:
    - restart grafana-server
