- name: Install OpenHPC Repository
  yum:
    name: http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm

- name: Install OpenHPC compilers
  yum:
    name: "{{ libraries }}"
  vars:
    libraries:
    - gnu8-compilers-ohpc
