---
- hosts: localhost
  remote_user: "{{ lookup('env','LOGNAME') }}"
  become: yes
  become_method: sudo
  roles:
    - boost-1_70
  environment:
    LD_LIBRARY_PATH: "/opt/ohpc/pub/compiler/gcc/8.3.0/lib64/:{{ ansible_env.LD_LIBRARY_PATH }}"
    PATH: "/opt/ohpc/pub/compiler/gcc/8.3.0/bin:{{ ansible_env.PATH }}"
    CC: "/opt/ohpc/pub/compiler/gcc/8.3.0/bin/gcc"
    CXX: "/opt/ohpc/pub/compiler/gcc/8.3.0/bin/g++"
