
- name: Add Apache Cassandra repository
  yum_repository:
    name: cassandra
    description: Apache Cassandra repository
    baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
    enabled: yes
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: https://www.apache.org/dist/cassandra/KEYS

- name: install the latest version of Apache Cassandra
  yum:
    name: cassandra
    state: latest 

# COPY CONFIG FOR CASSANDRA SHOULD COME HERE.
#- name: Copy cassandra conf file
#  copy:
#    src: etc/cassandra/cassandra.yml
#    dest: /etc/cassandra/cassandra.yml
#    backup: yes


#- name: Start service cassandra, if not started
#  service:
#    name: cassandra
#    state: started 

# daemon_reload flushes registry.
- systemd:  name=cassandra enabled=no daemon_reload=yes
- systemd:  name=cassandra enabled=yes
- systemd:  name=cassandra state=restarted 

