- name: Download and unpack boost_1_70_0
  unarchive:
    src: https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Bootstrap
  shell: ./bootstrap.sh --prefix=/opt/boost
  args:
    chdir: /tmp/boost_1_70_0/

- name: Install Boost
  shell: ./b2 install > install.log
  args:
    chdir: /tmp/boost_1_70_0/

- name: Remove Boost source folder
  file:
    path: /tmp/boost_1_70_0
    state: absent
