---
- hosts: localhost
  remote_user: "{{ lookup('env','LOGNAME') }}"
  become: yes
  become_method: sudo
  roles:
    - cassandra
  environment:
    LD_LIBRARY_PATH: "{{ lookup('env','LD_LIBRARY_PATH') }}" 
    PATH: "{{ lookup('env','PATH') }}"
    CC: "{{ lookup('env','CC') }}"
    CXX: "{{ lookup('env','CXX') }}"
