---
- hosts: localhost
  remote_user: "{{ lookup('env','LOGNAME') }}"
  become: yes
  become_method: sudo
  roles:
    - mongodb
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}" 
    https_proxy: "{{ lookup('env','https_proxy') }}" 
