- name: Install python-pip Centos
  yum:
    name: python-pip
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Twiddler
  pip:
    name: supervisor_twiddler

- name: Copy twiddler gui configuration file
  copy:
    src: etc/twiddler.ini
    dest: /etc/supervisord.d/
  notify:
    - restart supervisord
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: add cronjob to clear 1-day-old logs from /log folder every day
  cron:
    name: "remove old logs"
    minute: "0"
    hour: "0"
    job: "find /log/ -type f -name '*.log' -mtime +1 -exec rm {} \\; >/dev/null 2>&1"