- name: Clone nlohmann/json
  git:
    repo: https://github.com/nlohmann/json.git
    dest: /opt/json
    version: v3.6.1

- name: Clone gabime/spdlog
  git: 
    repo: https://github.com/gabime/spdlog.git
    dest: /opt/spdlog
    version: v1.3.1

- name: nemequ/hedley
  git:
    repo: https://github.com/nemequ/hedley.git
    dest: /opt/hedley
    version: v9

- name: Clone whoshuu/cpr
  git:
    repo: https://github.com/whoshuu/cpr
    dest: /opt/cpr
    version: 1.3.0

- file:
    path: /opt/cpr/build
    state: directory

- name: Run cmake3 in cpr
  cmake: 
    source_dir: /opt/cpr
    binary_dir: /opt/cpr/build
    target: cpr
    build_type: Release
    executable: /usr/bin/cmake3
    cache_vars: {"USE_SYSTEM_CURL": "ON", "BUILD_CPR_TESTS": "OFF", "CMAKE_CXX_FLAGS": "-fPIC"}

- name: Clone zeromq/libzmq
  git:
    repo: https://github.com/zeromq/libzmq.git
    dest: /opt/libzmq
    version: v4.3.2

- file:
    path: /opt/libzmq/build
    state: directory

- name: Run cmake3 in zmq
  cmake:
    source_dir: /opt/libzmq
    binary_dir: /opt/libzmq/build
    target: libzmq
    build_type: Release
    executable: /usr/bin/cmake3

    # Build libzmq with libsodium instead of the built-in tweetnacl.
    # Fixed zmq::context_t dtor on daqpy `down` command when libzmq curve security is enabled.
    cache_vars: {"WITH_LIBSODIUM": "ON"}

- name: Download and unpack xmlrpc-c
  unarchive:
    src: https://iweb.dl.sourceforge.net/project/xmlrpc-c/Xmlrpc-c%20Super%20Stable/1.51.06/xmlrpc-c-1.51.06.tgz
    dest: /tmp/
    remote_src: yes

- name: Configure xmlrpc-c makefile
  shell: ./configure --disable-wininet-client  --disable-curl-client --disable-libwww-client --disable-cgi-server
  args:
    chdir: /tmp/xmlrpc-c-1.51.06/

- name: Make and install xmlrpc-c
  shell: make ; make install
  args:
    chdir: /tmp/xmlrpc-c-1.51.06/
