# Enrico.Gamberini@cern.ch

- name: Clone nlohmann/json
  git:
    repo: https://github.com/nlohmann/json.git
    dest: /opt/json
    version: v3.6.1

- name: Clone gabime/spdlog
  git: 
    repo: https://github.com/gabime/spdlog.git
    dest: /opt/spdlog
    version: v1.3.1
