- name: Install python3-devel
  yum:
    name: python3-devel

- name: Install gunicorn
  pip:
    name: gunicorn
    executable: pip3

- name: Install gevent
  pip:
    name: gevent
    executable: pip3

- name: Install redis client
  pip:
    name: redis
    executable: pip3

- name: Install flask
  pip:
    name: Flask
    executable: pip3

- name: Install flask-redis
  pip:
    name: Flask-Redis
    executable: pip3

- name: Install flask-caching
  pip:
    name: Flask-Caching
    executable: pip3

- name: Install flask-restful
  pip:
    name: Flask-Restful
    executable: pip3

- name: Install flask_scss
  pip:
    name: flask_scss
    executable: pip3

- name: Install apispec
  pip:
    name: apispec
    executable: pip3

- name: Install pymongo
  pip:
    name: pymongo
    executable: pip3

- name: Install marshmallow
  pip:
    name: marshmallow
    executable: pip3

- name: Install webargs
  pip:
    name: webargs
    executable: pip3

- name: Install flask-apispec
  pip:
    name: flask-apispec
    executable: pip3

- name: Install flask-login
  pip:
    name: flask-login
    executable: pip3

- name: Open port 5000 on firewalld for Flask
  firewalld:
    zone: public
    port: 5000/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
