#
# Filename: roles/web-deps/tasks/main.yml
# Author  : Roland Sipos - rsipos@cern.ch
#
---

- name: Install gunicorn
  command: pip3 install gunicorn

- name: Install gevent
  command: pip3 install gevent

- name: Install redis client
  command: pip3 install redis

- name: Install flask
  command: pip3 install Flask

- name: Install flask-redis
  command: pip3 install Flask-Redis

- name: Install flask-caching
  command: pip3 install Flask-Caching

- name: Install flask-restful
  command: pip3 install Flask-Restful

- name: Install apispec
  command: pip3 install apispec

- name: Install marshmallow
  command: pip3 install marshmallow

- name: Install webargs
  command: pip3 install webargs

- name: Install flask-apispec
  command: pip3 install flask-apispec

- name: Install flask-login
  command: pip3 install flask-login

- name: Open port 5000 on firewalld for Flask
  firewalld:
    zone: public
    port: 5000/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
